@startuml
'https://plantuml.com/sequence-diagram

class App{
    start()
}

class MenuController{
TextField MonetaryValueInput
TextField SerialNumberInput
TextField NameInput

Label ErrorSN

Button ConfirmButton;

TableView<Item> listItem
TableColumn<Item, Double> vals
TableColumn<Item, String> sers
TableColumn<Item, String> names

public void AddItemClicked(ActionEvent event)
public void ValidateButtonPressed(ActionEvent event)
public void CancelButtonPressed(ActionEvent event)
public void changeNameEdit(TableColumn.CellEditEvent<Item,String> editedCell)
public void changeValueEdit(TableColumn.CellEditEvent<Item,String> editedCell)
public void changeSNEdit(TableColumn.CellEditEvent<Item,String> editedCell)

public void ExitAppClicked(ActionEvent event)

initialize(URL location, ResourceBundle rb)
}

class Item{
SimpleDoubleProperty value
SimpleStringProperty S_Number
SimpleStringProperty name

public Item(String value, String S_Number, String name)

public static boolean ValidName(String cur_name)
public static boolean ValidSN(String cur_SN)
public static boolean ValidPrice(String cur_price)
public static int NotMatchSN
public static ObservableList<Item> addItem

getters()
setters()
}

class Items{
List<Item> Serial_Items
}


@enduml